// What each starter quote means, shown beside it in the Home banner (option "open text").
// Keyed by the exact quote text; quotes you add yourself simply show without a note.
// [source, explanation]. Explanations keep to the quote's own sense, about life in general.
(function () {
  'use strict';
  const NOTES = {
    'Waste no more time arguing about what a good man should be. Be one.': ['Meditations 10.16',
      'Marcus is impatient with himself here. Talking about virtue, reading about it and judging others by it are easy. Being kind, honest and fair in the next moment is the only part that counts, and it is always within reach.'],
    'The impediment to action advances action. What stands in the way becomes the way.': ['Meditations 5.20',
      'Every obstacle is also an opportunity to practise something: patience when things are slow, courage when they are frightening, kindness when people are difficult. The mind can turn whatever blocks it into material for becoming better.'],
    'Very little is needed to make a happy life; it is all within yourself, in your way of thinking.': ['Meditations 7.67',
      'Happiness does not depend on owning more or on circumstances going your way. It comes from how you see things. A grateful, calm and honest way of thinking makes an ordinary life feel rich.'],
    'If it is not right, do not do it; if it is not true, do not say it.': ['Meditations 12.17',
      'A whole philosophy in two lines. Marcus reduces a good life to two simple tests you can apply in any moment: is this action right, and is this word true? If not, leave it.'],
    'At dawn, when you have trouble getting out of bed, tell yourself: I have to go to work, as a human being.': ['Meditations 5.1',
      'Even an emperor struggled to leave a warm bed. Marcus reminds himself that he was not made for comfort alone. Getting up to live, to be useful and to do his part is what being human asks of each of us.'],
    'Confine yourself to the present.': ['Meditations 7.29',
      'Most worry lives in the past or the future. Only this moment is actually in your hands, and it is always manageable. Bringing your attention back to now is the simplest way to steady the mind.'],
    'Do every act of your life as though it were the very last act of your life.': ['Meditations 2.5',
      'This is not meant to be gloomy. If this were your last act, you would do it with full attention, without hurry or pretence. Marcus asks for that same care and sincerity in everything, however small.'],
    'The soul becomes dyed with the colour of its thoughts.': ['Meditations 5.16',
      'Like cloth left in dye, the mind takes on the colour of what it dwells on. Repeated thoughts of resentment darken it; repeated thoughts of gratitude and goodness brighten it. We become what we keep thinking.'],
    'The best revenge is not to be like your enemy.': ['Meditations 6.6',
      'When someone wrongs you, the urge is to strike back in the same way. Marcus sees that this would only make you more like them. Staying decent is the one answer that leaves you untouched.'],
    'How much more harmful are the consequences of anger than the causes of it.': ['Meditations 11.18',
      'The thing that made us angry is usually small. What anger then makes us say and do, and the damage it leaves behind, is far greater. Losing your temper hurts you more than the offence ever could.'],
    'Loss is nothing else but change, and change is Nature’s delight.': ['Meditations 9.35',
      'Everything in nature is always changing: seasons, rivers, our own bodies. What we call loss is that same change touching something we love. Seeing it as natural makes it easier to bear, and to let go.'],
    'Never let the future disturb you. You will meet it, if you have to, with the same weapons of reason which today arm you against the present.': ['Meditations 7.8',
      'Worrying about tomorrow assumes you will face it unprepared. But you will bring the same judgement, courage and calm that are getting you through today. There is no need to suffer the future twice.'],
    'Dwell on the beauty of life. Watch the stars, and see yourself running with them.': ['Meditations 7.47',
      'Looking up at the night sky shrinks our worries to their true size. Marcus invites us to see ourselves as part of that vast, beautiful order, moving with it rather than apart from it.'],
    'Accept the things to which fate binds you, and love the people with whom fate brings you together, but do so with all your heart.': ['Meditations 6.39',
      'We do not choose our family, our time or many of our circumstances. Marcus says embrace them fully anyway. Half-hearted acceptance breeds resentment; wholehearted love turns a given life into a chosen one.'],
    'Look within. Within is the fountain of good, and it will ever bubble up, if you will ever dig.': ['Meditations 7.59',
      'Goodness is not something we must find outside ourselves. It is already within, like a spring underground. Reflection, honesty and effort are the digging that brings it to the surface again and again.'],
    'Do not act as if you were going to live ten thousand years. While you live, while it is in your power, be good.': ['Meditations 4.17',
      'We put off being kind, forgiving or brave as if time were endless. It is not. Marcus reminds himself that life is short and the chance to be good is now, while it is still possible.'],
    'Reject your sense of injury and the injury itself disappears.': ['Meditations 4.7',
      'Much of the pain in an insult comes from our own judgement that we have been harmed. Let go of that judgement and the sting fades. Others can act against us, but only we can decide to feel wounded.'],
    'The universe is change; our life is what our thoughts make it.': ['Meditations 4.3',
      'Nothing around us stays the same, and we cannot hold it still. What we can shape is how we see it. Two people can live the same day; their thoughts make one of them content and the other miserable.'],
    'Let not your mind run on what you lack as much as on what you have already.': ['Meditations 7.27',
      'The mind easily fixes on what is missing. Marcus suggests the opposite habit: count what you already have and imagine how much you would miss it. Gratitude turns the same life into a fuller one.'],
    'Be like the rocky headland on which the waves constantly break. It stands firm, and round it the seething waters are laid to rest.': ['Meditations 4.49',
      'Life will keep sending waves: setbacks, criticism, bad luck. The headland does not fight them or run from them; it simply stays itself, and the waves grow calm around it. Steadiness outlasts turmoil.'],
    'Never esteem anything as of advantage to you that will make you break your word or lose your self-respect.': ['Meditations 3.7',
      'Some gains come at the price of our integrity. Marcus says no such gain is real. Whatever you win by betraying a promise or yourself costs more than it gives, because character is the one thing worth keeping.'],
    'Nowhere can a man find a quieter or more untroubled retreat than in his own soul.': ['Meditations 4.3',
      'People look for peace in holidays, the countryside or the sea. Marcus reminds himself that the quietest place is always with him: his own mind. A few moments of turning inward can bring calm anywhere.'],
    'The art of living is more like wrestling than dancing.': ['Meditations 7.61',
      'Dancing follows a known routine; wrestling means meeting sudden, unexpected moves. Life is the second kind. We need to stay alert, balanced and ready to adapt, not expect everything to go to plan.'],
    'Think of yourself as dead. You have lived your life. Now take what’s left and live it properly.': ['Meditations 7.56',
      'Imagine your life were already over, then treat every day after that as a gift. Freed from the fear of losing it, you can spend the time that is left calmly, wisely and well.'],
    'Whatever happens at all happens as it should.': ['Meditations 4.10',
      'Marcus believed the world follows a rational order. Even when events hurt, they are part of a larger whole we cannot fully see. Accepting this brings peace, instead of fighting what has already happened.'],
    'We suffer more often in imagination than in reality.': ['Letters to Lucilius 13',
      'Most of what we dread never happens, and what does is rarely as bad as we pictured. Seneca notices that our fears run far ahead of events, so we suffer many times over for things that may never come.'],
    'It is not that we have a short time to live, but that we waste a lot of it.': ['On the Shortness of Life 1',
      'People complain that life is short. Seneca disagrees: it is long enough if it is used well. The trouble is how much of it slips away in distraction, busyness and waiting, without ever being truly lived.'],
    'Begin at once to live, and count each separate day as a separate life.': ['Letters to Lucilius 101',
      'We often treat now as a rehearsal for a real life that starts later. Seneca says begin today. If each day is lived as a complete life, with its own morning, fullness and end, nothing is ever left unlived.'],
    'While we are postponing, life speeds by.': ['Letters to Lucilius 1',
      'Every “later” feels harmless on its own, but together they add up to a life. Time does not wait while we hesitate. The things we keep putting off are quietly being given up.'],
    'Hold every hour in your grasp. Lay hold of today’s task, and you will not need to depend so much upon tomorrow’s.': ['Letters to Lucilius 1',
      'Seneca’s first letter is about time. If you fully use the hour you are in, you stop relying on an uncertain tomorrow. A life made of well-held hours needs far less hope in the future.'],
    'If a man does not know to which port he is sailing, no wind is favourable.': ['Letters to Lucilius 71',
      'Without knowing what we want from life, every chance and every change feels wrong. Once we know what matters most to us, almost any wind can carry us towards it.'],
    'It is not because things are difficult that we do not dare; it is because we do not dare that they are difficult.': ['Letters to Lucilius 104',
      'We say things are too hard, so we hold back. Seneca turns that around: it is our holding back that makes them seem hard. Courage often shrinks a challenge to its real, manageable size.'],
    'No man was ever wise by chance.': ['Letters to Lucilius 76',
      'Wisdom is not luck or talent. Seneca, still studying in his sixties, tells his friend that a clear and steady mind is built like any craft: through daily practice, reflection and effort.'],
    'As long as you live, keep learning how to live.': ['Letters to Lucilius 76',
      'Living well is a skill we never finish learning. Each age brings new questions, losses and joys. Seneca saw no shame in being a student of life until the very end.'],
    'Wherever there is a human being, there is an opportunity for a kindness.': ['On the Happy Life 24',
      'Kindness does not need a special occasion or a particular kind of person. Every encounter, with a stranger or someone close, is a chance to do a little good.'],
    'Associate with those who will make a better man of you.': ['Letters to Lucilius 7',
      'We slowly become like the people around us. Seneca advises choosing company that lifts us: people whose habits, values and conversation draw out our best, and welcoming those we can help in turn.'],
    'The primary sign of a well-ordered mind is a man’s ability to remain in one place and linger in his own company.': ['Letters to Lucilius 2',
      'Restlessness, always needing somewhere new or someone else, is a sign of an unsettled mind. Being content to stay still and enjoy your own company shows inner peace.'],
    'Life is long if you know how to use it.': ['On the Shortness of Life 2',
      'Length of life is not just a number of years. A life used with attention, for what truly matters, feels full and long. A life frittered away feels short however long it lasts.'],
    'Every day should be regulated as if it closed the series.': ['Letters to Lucilius 12',
      'Live each day as if it might be the last in the line: complete and settled, nothing important left undone. Then whatever comes next is a bonus rather than a debt.'],
    'He suffers more than is necessary, who suffers before it is necessary.': ['Letters to Lucilius 98',
      'Dreading a hardship in advance means living it twice. Seneca suggests meeting troubles when they actually arrive, rather than letting fear stretch them across the days before.'],
    'Whatever can happen at any time can happen today.': ['On Tranquillity of Mind 11',
      'Misfortune does not follow a schedule. Remembering this is not meant to make us anxious, but prepared and grateful: we hold what we love more gently, and are less shaken if it changes.'],
    'No man is more unhappy than he who never faces adversity, for he is not permitted to prove himself.': ['On Providence 3',
      'A life without difficulty never shows what we are made of. Hardship is where strength, patience and character are discovered. Seneca almost pities the person who has never been tested.'],
    'Fire tests gold, misfortune tests brave men.': ['On Providence 5',
      'Just as heat reveals whether gold is pure, hard times reveal a person’s true character. Courage is not known in comfort; it shows itself only when life becomes difficult.'],
    'The greatest obstacle to living is expectancy, which hangs upon tomorrow and loses today.': ['On the Shortness of Life 9',
      'Always waiting for life to begin “when” something happens means never living now. Seneca warns that expectation trades the one day we certainly have for a tomorrow that is not promised.'],
    'Putting things off is the biggest waste of life: it snatches away each day as it comes, and denies us the present by promising the future.': ['On the Shortness of Life 9',
      'Delay feels free, but it quietly costs us each day. By promising ourselves a future, we give away the present, which is the only time we ever actually live in.'],
    'Most powerful is he who has himself in his own power.': ['Letters to Lucilius 90',
      'Real power is not control over others but mastery of yourself: your temper, your desires, your fears. Whoever has that cannot easily be ruled by anyone or anything.'],
    'It is quality rather than quantity that matters.': ['Letters to Lucilius 45',
      'Seneca was writing about books: better to know a few deeply than skim many. The same is true of friends, possessions and years. Depth gives life its richness, not number.'],
    'Treat your inferiors as you would be treated by your betters.': ['Letters to Lucilius 47',
      'Written about how slaves were treated in Rome, this is Seneca’s version of the golden rule. Whatever power we have over others should be used with the respect we would want from those above us.'],
    'The mind must be given relaxation. It will rise improved and sharper after a good break.': ['On Tranquillity of Mind 17',
      'Seneca, usually so serious, defends rest. A field left fallow grows better crops. A mind given time to play and wander returns clearer and stronger than one kept constantly strained.'],
    'Until we have begun to go without them, we fail to realise how unnecessary many things are.': ['Letters to Lucilius 123',
      'We assume we need many comforts until we try living without them. Going without shows how little we truly require, and frees us from fearing their loss.']
  };
  // Look up by text, ignoring curly vs straight quotes and extra spaces.
  const norm = t => String(t || '').replace(/[\u2018\u2019]/g, "'").replace(/[\u201c\u201d]/g, '"').replace(/\s+/g, ' ').trim();
  const byText = {};
  Object.keys(NOTES).forEach(k => { byText[norm(k)] = NOTES[k]; });
  window.DS_QUOTE_NOTES = { get: body => byText[norm(body)] || null };
})();
