// Reports: weekly and monthly reports (generated by the server on Sunday 6pm and the last day of the month),
// an archive page, and deep links from the report emails (#plan=week:YYYY-MM-DD, #plan=month:YYYY-MM-DD, #reports).
(function () {
  'use strict';
  const DS = window.DS;
  if (!DS) return;
  const { sb, q, el, state, toast, refresh, fmt, addDays, addMonths } = DS;

  /* deep links from the emails */
  const m = location.hash.match(/^#plan=(week|month):(\d{4}-\d{2}-\d{2})$/);
  if (m || location.hash === '#reports') {
    const view = m ? m[1] : 'reports';
    state.view = view;
    if (m) state.cursor = m[2];
    try { history.replaceState(null, '', '#' + view); } catch (e) {}
    if (document.getElementById('main')) DS.go(view, m ? m[2] : undefined);
  }

  /* add "Reports" to the top navigation (before Settings) */
  function addNav() {
    const nav = document.querySelector('nav.nav');
    if (!nav || nav.querySelector('[data-nav="reports"]')) return;
    const btn = el('button', { 'data-nav': 'reports', 'aria-current': state.view === 'reports' ? 'page' : null, onclick: () => { openId = null; DS.go('reports'); } }, 'Reports');
    const settings = [...nav.children].find(b => b.textContent.trim() === 'Settings');
    nav.insertBefore(btn, settings || null);
  }
  const app = document.getElementById('app');
  if (app) new MutationObserver(addNav).observe(app, { childList: true });
  addNav();

  const mins = m => m < 60 ? `${m}m` : `${Math.floor(m / 60)}h${m % 60 ? ' ' + (m % 60) + 'm' : ''}`;
  const pct = (a, b) => b ? Math.round(a / b * 100) : 0;
  const label = r => r.kind === 'week'
    ? `${fmt(r.period_start, { day: 'numeric', month: 'short' })} \u2013 ${fmt(addDays(r.period_start, 6), { day: 'numeric', month: 'short', year: 'numeric' })}`
    : fmt(r.period_start, { month: 'long', year: 'numeric' });
  let openId = null;

  async function emailNow(kind, btn) {
    btn.disabled = true;
    try {
      const { data, error } = await sb.functions.invoke('reminders', { body: { report: kind } });
      if (error) throw error;
      toast(data?.emailed ? `Done. This ${kind}\u2019s report so far is in your inbox.` : 'The report was saved, but the email didn\u2019t send. Check the Resend key.');
      refresh();
    } catch (e) { toast('Couldn\u2019t create the report. Try again in a moment.'); btn.disabled = false; }
  }

  async function viewReports() {
    const rows = await q(sb.from('reports').select('*').order('period_start', { ascending: false }).order('kind', { ascending: false }).limit(200));
    if (openId) { const r = rows.find(x => x.id === openId); if (r) return detail(r); openId = null; }
    const b1 = el('button', { class: 'rp-btn', onclick: e => emailNow('week', e.currentTarget) }, 'Email me this week so far');
    const b2 = el('button', { class: 'rp-btn', onclick: e => emailNow('month', e.currentTarget) }, 'Email me this month so far');
    return el('div', {},
      el('div', { class: 'head' }, el('h1', {}, 'Reports')),
      el('p', { class: 'meta' }, 'A weekly report arrives every Sunday at 6pm and a monthly one on the evening of the last day of the month, by email and here.'),
      el('div', { class: 'rp-actions' }, b1, b2),
      rows.length ? el('div', { class: 'rp-grid' }, rows.map(r => {
        const t = r.data.tasks || { done: 0, total: 0 };
        return el('button', { class: `rp-card k-${r.kind}`, onclick: () => { openId = r.id; refresh(); window.scrollTo(0, 0); } },
          el('span', { class: 'rp-kind' }, r.kind === 'week' ? 'Weekly report' : 'Monthly report'),
          el('b', { class: 'rp-title' }, label(r)),
          el('div', { class: 'obar' }, el('i', { style: `width:${pct(t.done, t.total)}%` })),
          el('span', { class: 'rp-sub' }, `${t.done}/${t.total} tasks done \u00b7 ${pct(t.done, t.total)}%`),
          el('span', { class: 'rp-sub' }, `${(r.data.wins || []).length} wins \u00b7 ${mins(r.data.focus_total || 0)} focus${r.emailed_at ? ' \u00b7 emailed' : ''}`));
      })) : el('p', { class: 'td-empty' }, 'No reports yet. Your first weekly report arrives on Sunday at 6pm, or use the buttons above for a preview now.'));
  }

  function detail(r) {
    const d = r.data, W = r.kind === 'week', t = d.tasks || { total: 0, done: 0, dropped: 0, carried: 0 };
    const now = pct(t.done, t.total), prev = d.prev && d.prev.total ? pct(d.prev.done, d.prev.total) : null;
    const kpi = (lbl, v, note) => el('div', { class: 'wk-kpi' }, el('span', {}, lbl), el('b', {}, v), note ? el('small', {}, note) : null);
    const tile = (title, ...kids) => el('section', { class: 'td-tile rp-tile' }, el('h2', {}, title), ...kids);
    const statusWord = s => s === 'done' ? (W ? 'Done' : 'Achieved') : s === 'dropped' ? 'Dropped' : `Rolling into next ${W ? 'week' : 'month'}`;
    const ctx = Object.entries(d.focus_by_context || {}).sort((a, b) => b[1] - a[1]);
    const top = ctx.length ? ctx[0][1] : 1;
    const next = W ? addDays(r.period_start, 7) : addMonths(r.period_start, 1);
    return el('div', {},
      el('button', { class: 'rp-back', onclick: () => { openId = null; refresh(); } }, '\u2190 All reports'),
      el('div', { class: 'head' }, el('h1', {}, W ? 'Week in review' : 'Month in review')),
      el('p', { class: 'meta' }, label(r) + (r.emailed_at ? ' \u00b7 emailed' : '')),
      el('div', { class: 'wk-kpis' },
        kpi('Tasks done', `${t.done}/${t.total}`, `${now}%${prev === null ? '' : ` \u00b7 ${now - prev >= 0 ? '+' : ''}${now - prev} pts vs last ${W ? 'week' : 'month'}`}`),
        kpi('Focus time', mins(d.focus_total || 0), ''),
        kpi('Wins', String((d.wins || []).length), ''),
        kpi('Avg energy', d.energy != null ? String(d.energy) : '\u2013', d.focus != null ? `focus ${d.focus}` : '')),
      el('div', { class: 'rp-cols' },
        tile(W ? 'Weekly priorities' : 'Monthly outcomes',
          (d.items || []).length ? el('ul', { class: 'rp-list' }, d.items.map(i => el('li', { class: 's-' + i.status },
            el('span', { class: 'rp-dot' }), el('span', {}, el('b', {}, i.title), el('small', {}, statusWord(i.status) + (i.kids ? ` \u00b7 ${i.kids_done}/${i.kids} ${W ? 'daily tasks' : 'weekly priorities'}` : '')))))) : el('p', { class: 'td-none' }, 'None were set.')),
        tile('Focus by context', ctx.length ? el('div', { class: 'rp-bars' }, ctx.map(([k, v]) => el('div', { class: 'rp-bar' },
          el('span', {}, k), el('div', { class: 'obar' }, el('i', { style: `width:${Math.round(v / top * 100)}%` })), el('b', {}, mins(v))))) : el('p', { class: 'td-none' }, 'No focus blocks logged.')),
        tile('Wins', (d.wins || []).length ? el('ul', { class: 'td-wins' }, d.wins.map(w => el('li', {}, el('span', {}, w.body, el('small', { class: 'rp-day' }, ' \u00b7 ' + fmt(w.day, { weekday: 'short', day: 'numeric' })))))) : el('p', { class: 'td-none' }, 'No wins logged.')),
        (d.notes || []).length ? tile('From your notes', el('ul', { class: 'rp-notes' }, d.notes.map(n => el('li', {}, el('b', {}, fmt(n.day, { weekday: 'short', day: 'numeric', month: 'short' })), el('p', {}, n.notes))))) : null,
        d.review?.reflection ? tile(W ? 'Your week review' : 'Your month review', el('p', { class: 'rp-quote' }, `\u201c${d.review.reflection}\u201d`)) : null,
        (d.stuck || []).length ? tile('Stuck tasks', el('ul', { class: 'rp-list' }, d.stuck.map(s => el('li', { class: 's-stuck' }, el('span', { class: 'rp-dot' }), el('span', {}, el('b', {}, s.title), el('small', {}, `carried \u00d7${s.carry_count}`))))),
          el('p', { class: 'td-none' }, 'Each has slipped at least three times. Schedule it, break it down or drop it.')) : null),
      el('div', { class: 'rp-cta' }, el('button', { class: 'mr-save', onclick: () => DS.go(r.kind, next) }, W ? `Plan the week of ${fmt(next, { day: 'numeric', month: 'short' })} \u2192` : `Set ${fmt(next, { month: 'long' })}\u2019s outcomes \u2192`)));
  }

  DS.views.reports = viewReports;
  if (state.user && state.view === 'reports') refresh();
})();
